from datetime import datetime

power_on_pvname = 'ACSW:LBNL:NW01:1POWERON'
power_off_pvname = 'ACSW:LBNL:NW01:1POWEROFF'
status_pvname = 'ACSW:LBNL:NW01:1POWERSTATEIN'
position_pvnames = ['USEG:LBNL_MMF:1:DS:ENCODER',
					'USEG:LBNL_MMF:1:DS:ENCODER.RVAL',
					'USEG:LBNL_MMF:1:DSBOT:AXIS_FAULT',
					'USEG:LBNL_MMF:1:DSBOT:AXIS_STATUS',
					'USEG:LBNL_MMF:1:DSBOT:MOTR.RBV',
					'USEG:LBNL_MMF:1:DSTOP:AXIS_FAULT',
					'USEG:LBNL_MMF:1:DSTOP:AXIS_STATUS',
					'USEG:LBNL_MMF:1:DSTOP:MOTR.RBV',
					'USEG:LBNL_MMF:1:PWR:SWITCH_STATUS',
					'USEG:LBNL_MMF:1:TLT:SWITCH_STATUS',
					'USEG:LBNL_MMF:1:US:ENCODER',
					'USEG:LBNL_MMF:1:US:ENCODER.RVAL',
					'USEG:LBNL_MMF:1:USBOT:AXIS_FAULT',
					'USEG:LBNL_MMF:1:USBOT:AXIS_STATUS',
					'USEG:LBNL_MMF:1:USBOT:MOTR.RBV',
					'USEG:LBNL_MMF:1:USTOP:AXIS_FAULT',
					'USEG:LBNL_MMF:1:USTOP:AXIS_STATUS',
					'USEG:LBNL_MMF:1:USTOP:MOTR.RBV',
					'USEG:LBNL_MMF:1:VAC:SWITCH_STATUS',
					]

def get_timestamp():
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')
